# Generated by Django 5.0.6 on 2024-05-23 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('capacidade', models.IntegerField()),
                ('tipo', models.CharField(choices=[('REUNIÂO', 'Sala de Reunião'), ('Laboratório', 'Laboratório'), ('AUDITÓRIO', 'Auditório'), ('SALA DE AULA', 'Sala de Aula'), ('Oficina', 'Oficina')], max_length=15)),
                ('projetor', models.BooleanField()),
                ('ar_condicionado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ReservaForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('responsavel', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('sala', models.ForeignKey(choices=[('REUNIÂO', 'Sala de Reunião'), ('Laboratório', 'Laboratório'), ('AUDITÓRIO', 'Auditório'), ('SALA DE AULA', 'Sala de Aula'), ('Oficina', 'Oficina')], on_delete=django.db.models.deletion.CASCADE, to='polls.sala')),
            ],
        ),
    ]
