# Generated by Django 5.0.6 on 2024-05-28 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='tipo',
            field=models.CharField(choices=[('REUNIÂO', 'Sala de Reunião'), ('Laboratório', 'Laboratório'), ('AUDITÓRIO', 'Auditório'), ('SALA DE AULA', 'Sala de Aula'), ('OFICINA', 'Oficina')], max_length=15),
        ),
        migrations.CreateModel(
            name='ReservaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('responsavel', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.sala')),
            ],
        ),
        migrations.DeleteModel(
            name='ReservaForm',
        ),
    ]
