# Generated by Django 5.0.6 on 2024-05-28 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_sala_tipo_reservamodel_delete_reservaform'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='descricao',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
