# Generated by Django 5.0.6 on 2024-06-01 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='imagens/'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
