# Generated by Django 5.0.6 on 2024-06-01 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_sala_imagem_alter_sala_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservamodel',
            old_name='data',
            new_name='dia',
        ),
    ]
