# Generated by Django 5.0.6 on 2024-06-02 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_rename_data_reservamodel_dia'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservamodel',
            name='event_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
